### ISSUE TITLE
mistake in user doc

### ISSUE THREAD

**Issue by mdutoo** [cgourdin/MartServer#45]
I guess that the following query sample in the [user doc](https://github.com/cgourdin/MartServer/blob/master/doc/userjson.md) should NOT contain the resource id but be merely http://localhost:8080/compute :

If you don't know the path of your resource, you can use its kind for example, for a compute, you can do this : curl -v -X GET http://localhost:8080/compute/a1cf3896-500e-48d8-a3f5-a8b3601bcdd8 -H "accept: application/json"

**Comment by cgourdin** [comment]
I was telling about path location of a resource, so you know the id but not the location of this resource.
If you use a GET query on http://localhost:8080/compute, **this** give a complete collection of resources for the kind "compute".

**Comment by mdutoo** [comment]
"you know the id but not the location of this resource" => shouldn't it be rather http://localhost:8080/a1cf3896-500e-48d8-a3f5-a8b3601bcdd8 (without compute) then ?

**Comment by cgourdin** [comment]
Yes it is :  you know the id but not the location of this resource, but the location of the resource may be : http://localhost:8080/myvm/myfoo/bar/a1cf3896-500e-48d8-a3f5-a8b3601bcdd8 

So if you call a get resource with the path : /a1cf3896-500e-48d8-a3f5-a8b3601bcdd8 you can't retrieve the resource (404) because the location is incorrect. If your resource is on the path "/", you retrieve your resource directly with /a1cf3896-500e-48d8-a3f5-a8b3601bcdd8.
My example is correct but doesn't give a complex location path like /foo/bar/myvm/a1cf3896-500e-48d8-a3f5-a8b3601bcdd8.

The kind is to used to retrieve the resource without an inbound path.

**Comment by mdutoo** [comment]
OK, I was misled, sorry.
